package:
  name: gdcm
  version: 2.4.4

source:
  url: http://sourceforge.net/projects/gdcm/files/gdcm%202.x/GDCM%202.4.4/gdcm-2.4.4.tar.bz2/download [not win]
  fn: gdcm-2.4.4.tar.bz2                      [not win]
  md5: c1fd2a9595236a03d114370e9c42ef48      [not win]
  # fn: VTK-5.10.1.win32-py2.6.exe             [win32 and py26]
  # fn: VTK-5.10.1.win-amd64-py2.6.exe         [win64 and py26]
  # fn: VTK-5.10.1.win32-py2.7.exe             [win32 and py27]
  # fn: VTK-5.10.1.win-amd64-py2.7.exe         [win64 and py27]

  patches:
    - vtk62.patch

build:
  number: 1                                  [linux]

requirements:
  build:
    - cmake                                  [linux]
    - python
    - swig
    - vtk >=6.2.0
    
  run:
    - python
    - vtk >=6.2.0

about:
  home: http://sourceforge.net/projects/gdcm/
  license: BSD
